djcrm/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='landing.html')),
    path('users/', include('users.urls', namespace='users')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
]

leads/urls.py
from .views import LeadCreateView, LeadDeleteView, LeadDetailView, LeadListView, LeadUpdateView, landing
from django.urls import path

app_name = 'leads'

urlpatterns = [
    path('', landing, name='landing-page'),
    path('detail/<int:pk>/', LeadDetailView, name='lead-detail'),
    path('update/<int:pk>/', LeadUpdateView.as_view(), name='lead-update'),
    path('list/', LeadListView.as_view(), name='lead-list'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('delete/<int:pk>/', LeadDeleteView.as_view(), name='lead-delete'),
]

leads/models.py
from users.models import UserProfile
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE) 
    agent = models.ForeignKey('Agent', null=True, blank=True, on_delete=models.SET_NULL)


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.email

leads/forms.py
from django import forms
from .models import Lead


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = [
            'first_name',
            'last_name',
            'age',
            'agent',
            'organization',
            ]


# class LeadForm(forms.Form):
    # first_name = forms.CharField()
#     last_name = forms.CharField()
#     age = forms.IntegerField(min_value=0)

leads/views.py
from django.core.mail import send_mail
from django.urls.base import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent, Lead
from leads.forms import LeadForm
from agents.mixins import OrganizerAndLoginRequiredMixin


def landing(request):
    return render(request, 'landing.html')

class LeadDetailView(LoginRequiredMixin, DetailView):
    queryset = Lead.objects.all()
    template_name = 'leads/lead_detail.html'

class LeadListView(LoginRequiredMixin, ListView):
    context_object_name = 'leads'

    def get_queryset(self):
        queryset = Lead.objects.all()
        user = self.request.user
        if user.is_organizer:
            queryset = queryset.filter(organization_id=user.user_profile.id)
        elif user.is_agent:
            queryset = queryset.filter(organization_id=user.agent.organization.id)
            queryset = queryset.filter(agent__user_id=user.id)
            return queryset
        return queryset


class LeadCreateView(OrganizerAndLoginRequiredMixin, CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadForm

    def get_success_url(self) -> str:
        return reverse('leads:lead-list')

    def form_valid(self, form):
        send_mail(
            subject='A new lead has been created',
            message='Go to the site to see the new lead',
            from_email="test@gmail.com",
            recipient_list=["test2@gmail.com"]
        )
        return super().form_valid(form)


class LeadUpdateView(OrganizerAndLoginRequiredMixin, UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadForm
    queryset = Lead.objects.all()

    def get_queryset(self):
        user = self.request.user
        queryset = Lead.objects.filter(organization_id=user.user_profile.id)
        return queryset

    def get_success_url(self) -> str:
        return reverse('leads:lead-list')

class LeadDeleteView(OrganizerAndLoginRequiredMixin, DeleteView):
    template_name = 'leads/lead_delete.html'

    def get_queryset(self):
        queryset = Lead.objects.all()
        user = self.request.user
        if user.is_organizer:
            queryset = queryset.filter(organization_id=user.user_profile.id)
        elif user.is_agent:
            queryset = queryset.filter(organization_id=user.agent.organization.id)
            queryset = queryset.filter(agent__user_id=user.id)
            return queryset
        return queryset

    def get_success_url(self) -> str:
        return reverse('leads:lead-list')

leads/templates/leads/lead_create.html
<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="ffffff">
</form>

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  <input type="submit" value="delete">
</form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'leads:lead-update' lead.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Mongolia</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone number</span>
          <span class="ml-auto text-gray-900">+7747420143717</span>
        </div>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex flex-wrap">
    <h1 class="text-4xl mb-4 mr-auto">Leads</h1>
    {% if user.is_organizer %}
      <a class='hover:text-blue-500 self-center text-lg ' href="{% url 'leads:lead-create' %}">Create a new lead</a>
    {% endif %}
    <div class="flex flex-wrap md:w-full -m-4">
      {% for lead in leads %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                {{ lead.first_name }} {{ lead.last_name }}
              </h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href="{% url 'leads:lead-detail' lead.id %}" class="mt-3 text-indigo-500 inline-flex items-center">
                View this lead.
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section> 
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'leads:lead-update' lead.pk  %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
        </div>
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="flex mr-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" value="Submit"/>
        </form>

        <button class="mt-5 flex mr-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Delete the lead</button>
        
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock content %}