agents/urls.py
from .views import AgentCreateView, AgentDeleteView, AgentDetailView, AgentListView, AgentUpdateView
from django.urls import path

app_name = 'agents'

urlpatterns = [
    # path('list/', lead_list, name='lead-list'),
    # path('create/', lead_create, name='lead-create'),
    # path('update/<int:pk>/', lead_update, name='lead-update'),
    path('list/', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('detail/<int:pk>/', AgentDetailView, name='agent-detail'),
    path('update/<int:pk>/', AgentUpdateView.as_view(), name='agent-update'),
    path('delete/<int:pk>/', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='landing.html')),
    path('users/', include('users.urls', namespace='users')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from users.models import CustomUser
from leads.models import Agent
from django import forms


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'email',
            ]

agents/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from agents.mixins import OrganizerAndLoginRequiredMixin
from django.urls.base import reverse
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic import ListView, CreateView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from random import randint
from leads.models import Agent
from .forms import AgentModelForm


class AgentListView(OrganizerAndLoginRequiredMixin, ListView):
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'

    def get_queryset(self):
        organization = self.request.user.user_profile
        return Agent.objects.filter(organization=organization)


class AgentCreateView(OrganizerAndLoginRequiredMixin, CreateView):
    template_name = 'agents/agent_create.html'
    form_class = AgentModelForm

    def get_success_url(self) -> str:
        return reverse('agents:agent-list')

    def form_valid(self, form):
        # form.instance.organization = self.request.user.user_profile
        user = form.instance
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{randint(1, 10000000)}")
        user.save()
        Agent.objects.create(user=user, organization=self.request.user.user_profile)
        send_mail(
            subject='A new lead has been created',
            message='Go to the site to see the new lead',
            from_email="test@gmail.com",
            recipient_list=[user.email]
        )
        return redirect('agents:agent-list')


class AgentDetailView(OrganizerAndLoginRequiredMixin, DetailView):
    template_name = 'agents/agent_detail.html'

    def get_queryset(self):
        organization = self.request.user.user_profile
        return Agent.objects.filter(organization=organization)

class AgentUpdateView(OrganizerAndLoginRequiredMixin, UpdateView):
    template_name = 'agents/agent_update.html'
    form_class = AgentModelForm
    queryset = Agent.objects.all()

    def get_queryset(self):
        organization = self.request.user.user_profile
        return Agent.objects.filter(organization=organization)

    def get_success_url(self) -> str:
        return reverse('agents:agent-list')

class AgentDeleteView(OrganizerAndLoginRequiredMixin, DeleteView):
    queryset = Agent.objects.all()
    template_name = 'agents/agent_delete.html'

    def get_queryset(self):
        organization = self.request.user.user_profile
        return Agent.objects.filter(organization=organization)

    def get_success_url(self) -> str:
        return reverse('agents:agent-list')

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="ffffff">
</form>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  <input type="submit" value="delete">
</form>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ agent.user.email }}
        </h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'agents:agent-update' agent.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Organization head email</span>
          <span class="ml-auto text-gray-900">{{ agent.organization.user.email }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone number</span>
          <span class="ml-auto text-gray-900">+7747420143717</span>
        </div>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex flex-wrap">
    <h1 class="text-4xl mb-4">Agents</h1>
    <a class='hover:text-blue-500 self-center text-lg ml-auto' href="{% url 'agents:agent-create' %}">Create a new agent</a>
    <div class="flex flex-wrap -m-4">
      {% for agent in agents %}
        <div class="p-4 lg:w-1/2  md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                {{ agent.emal }}
              </h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href="{% url 'agents:agent-detail' agent.id %}" class="mt-3 text-indigo-500 inline-flex items-center">
                View this agent.
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section> 
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.email }} </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent-detail' agent.pk  %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'agents:agent-update' agent.pk  %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
        </div>
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="flex mr-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" value="Submit"/>
        </form>

        <a href="{% url 'agents:agent-delete' agent.pk %}" class="mt-5 flex mr-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Delete the agent</a>
        
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock content %}