agents/urls.py
from .views import AgentCreateView, AgentDeleteView, AgentDetailView, AgentListView, AgentUpdateView
from django.urls import path

app_name = 'agents'

urlpatterns = [
    # path('list/', lead_list, name='lead-list'),
    # path('create/', lead_create, name='lead-create'),
    # path('update/<int:pk>/', lead_update, name='lead-update'),
    path('list/', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('detail/<int:pk>/', AgentDetailView, name='agent-detail'),
    path('update/<int:pk>/', AgentUpdateView.as_view(), name='agent-update'),
    path('delete/<int:pk>/', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='landing.html')),
    path('users/', include('users.urls', namespace='users')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
]

leads/urls.py
from .views import LeadCreateView, LeadDeleteView, LeadDetailView, LeadListView, LeadUpdateView, landing
from django.urls import path

app_name = 'leads'

urlpatterns = [
    path('', landing, name='landing-page'),
    path('detail/<int:pk>/', LeadDetailView, name='lead-detail'),
    path('update/<int:pk>/', LeadUpdateView.as_view(), name='lead-update'),
    path('list/', LeadListView.as_view(), name='lead-list'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('delete/<int:pk>/', LeadDeleteView.as_view(), name='lead-delete'),
]

users/urls.py
from users.views import SignUpView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls.conf import path

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    # path('update/<int:pk>/', LeadUpdateView.as_view(), name='lead-update'),
    # path('list/', LeadListView.as_view(), name='lead-list'),
    # path('create/', LeadCreateView.as_view(), name='lead-create'),
    # path('delete/<int:pk>/', LeadDeleteView.as_view(), name='lead-delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'tailwind.css' %}" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="max-w-6xl m-auto">
      {% include 'navbar.html' %}
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% block content %}
  <section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-8 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Simple CRM</h1>
        <p class="mb-8 leading-relaxed">This is a customer management service</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Simple CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if user.is_authenticated  %}
        {% if user.is_organizer %}
          <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
        {% endif %}
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      Logged in: {{ user.email }}
      <a href="{% url 'users:logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
         Log out
         <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
           <path d="M5 12h14M12 5l7 7-7 7"></path>
         </svg>
       </a>
      {% else %}
      <a href="{% url 'users:sign-up' %}" class="mr-5 hover:text-gray-900">Sign up</a>
      <a href="{% url 'users:login' %}"='#' class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      {% endif %}
    </nav>
  </div>
</header>